### PR TITLE
added support for Bootstrap 3 (fluid)

### PR DESCRIPTION
**Pull request by chetan**
sorry about the trimmed spaces. I could maybe submit a pull without them if you prefer.

### CODE REVIEW

**Comment by alefeuvre** [comment]
Great, thank you Chetan (and sorry for the late reply)!

**Comment by balddog** [comment]
Thanks for the great work.  What is the framework code (e.g., b3) to go inside the <body data-grid-framework="b3f"> tag for Bootstrap 3 fluid?

**Comment by chetan** [comment]
@balddog it's 'b3f'

**Comment by balddog** [comment]
Thank you!  I should have tried that before posting because I suspected it might be.

**Comment by balddog** [comment]
Is it possible to view grids within a div?

**Comment by alefeuvre** [comment]
Thanks Chetan for the quick answer. I'll also update the code on snipt to add the 'b3f' code.

I'm not sure I quite understand your question about divs. Are you talking about cols within cols? Or maybe applying the displayer to a specific div rather than to the full page? (If it's the latter what you meant, no, it isn't possible. The grid displayer is embedded in a div with the 'container', or 'container-fluid', class.) 

-----Original Message-----

**Comment by alefeuvre** [comment]
And thanks for your message, I'm glad you like the bookmarklet.

-----Original Message-----

**Comment by chetan** [comment]
I think @balddog is referring to [nested columns](http://getbootstrap.com/css/#grid-nesting). It's not supported currently and I'm not sure it could be added too easily..

**Comment by alefeuvre** [comment]
Yes, nested columns, that's what I meant with 'cols within cols'. No, 
it's not supported indeed, and I don't see an easy way to display them. 
Suggestions are most welcome!

**Pull request merged**
